"""empty message

Revision ID: 1def126b8921
Revises: 6d177bc1113e
Create Date: 2020-05-06 23:59:31.796105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1def126b8921'
down_revision = '6d177bc1113e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'grade',
        '年级班级表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.add_column('users', sa.Column('sex', sa.Integer(), nullable=True, comment='性别 1男  0女'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_table_comment(
        'grade',
        existing_comment='年级班级表',
        schema=None
    )
    # ### end Alembic commands ###
