"""empty message

Revision ID: 3a7d87625646
Revises: 42d61d9fd5c9
Create Date: 2020-05-02 23:21:31.156792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a7d87625646'
down_revision = '42d61d9fd5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='班级名称'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('teacher_id', sa.Integer(), nullable=True, comment='教师ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_table('grade')
    # ### end Alembic commands ###
