"""empty message

Revision ID: 42d61d9fd5c9
Revises: 04e41118fc81
Create Date: 2020-05-02 23:14:51.457200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42d61d9fd5c9'
down_revision = '04e41118fc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.add_column('teacher', sa.Column('phone', sa.String(length=50), nullable=True, comment='手机号'))
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('teacher', 'phone')
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
