"""empty message

Revision ID: 476971f5eb8c
Revises: 3a7d87625646
Create Date: 2020-05-03 16:01:57.249460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '476971f5eb8c'
down_revision = '3a7d87625646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ask_approved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='审批人'),
    sa.Column('ask_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态0 未审批  1 已审批   -1 已拒绝 2已转交'),
    sa.Column('approved_at', sa.DateTime(), nullable=False, comment='审批时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='审批说明'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ask_leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True, comment='请假事由'),
    sa.Column('start_at', sa.DateTime(), nullable=False, comment='请假开始时间'),
    sa.Column('end_at', sa.DateTime(), nullable=False, comment='请假结束时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态 0已发起 1审批中 2 完成审批  3请假完成  -1拒绝'),
    sa.Column('send_user', sa.Integer(), nullable=True, comment='发起人'),
    sa.Column('ask_user', sa.Integer(), nullable=True, comment='请假用户  谁要请假'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True, comment='车牌号'),
    sa.Column('car_type', sa.String(length=100), nullable=True, comment='车辆类型'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='品牌'),
    sa.Column('colour', sa.String(length=100), nullable=True, comment='颜色'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态默认'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色ID'),
    sa.Column('access_id', sa.Integer(), nullable=True, comment='权限ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True, comment='上级'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='描述'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序', serve_default=100),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('staff', sa.Column('phone', sa.String(length=50), nullable=True, comment='电话'))
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.add_column('student_parent', sa.Column('phone', sa.String(length=50), nullable=True, comment='手机'))
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('student_parent', 'phone')
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('staff', 'phone')
    op.drop_table('roles')
    op.drop_table('role_access')
    op.drop_table('car')
    op.drop_table('ask_leave')
    op.drop_table('ask_approved')
    op.drop_table('access_records')
    # ### end Alembic commands ###
