"""empty message

Revision ID: 6d177bc1113e
Revises: a63522a5bd20
Create Date: 2020-05-05 22:20:55.621943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d177bc1113e'
down_revision = 'a63522a5bd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('sort', sa.Integer(), nullable=True))
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('grade', 'sort')
    # ### end Alembic commands ###
