"""empty message

Revision ID: 70b0020824f3
Revises: 60c148a1ce89
Create Date: 2020-05-04 21:12:35.254432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70b0020824f3'
down_revision = '60c148a1ce89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('access_id', sa.Integer(), nullable=True, comment='权限ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('access', sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('access', sa.Column('is_del', sa.Boolean(), nullable=True, comment='是否删除'))
    op.add_column('access', sa.Column('name', sa.String(length=100), nullable=True, comment='节点名称'))
    op.add_column('access', sa.Column('sort', sa.Integer(), nullable=True, comment='排序'))
    op.add_column('access', sa.Column('status', sa.Integer(), nullable=True, comment='状态'))
    op.add_column('access', sa.Column('url', sa.String(length=200), nullable=False, comment='路由正则匹配'))
    op.alter_column('access', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='创建用户',
               existing_comment='用户ID',
               existing_nullable=True)
    op.create_table_comment(
        'access',
        '权限表',
        existing_comment=None,
        schema=None
    )
    op.drop_column('access', 'access_id')
    op.create_table_comment(
        'menu',
        '菜单表',
        existing_comment='菜单权限表',
        schema=None
    )
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student_parent', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('student', 'grade_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('staff', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.create_table_comment(
        'menu',
        '菜单权限表',
        existing_comment='菜单表',
        schema=None
    )
    op.add_column('access', sa.Column('access_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='权限ID'))
    op.drop_table_comment(
        'access',
        existing_comment='权限表',
        schema=None
    )
    op.alter_column('access', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               existing_comment='创建用户',
               existing_nullable=True)
    op.drop_column('access', 'url')
    op.drop_column('access', 'status')
    op.drop_column('access', 'sort')
    op.drop_column('access', 'name')
    op.drop_column('access', 'is_del')
    op.drop_column('access', 'create_at')
    op.drop_table('user_access')
    # ### end Alembic commands ###
